### ISSUE TITLE
Use this in my react native application.

### ISSUE THREAD

**Issue by mustafa-taheri** [mygulamali/mumineen_calendar_js#2]
Hi @mygulamali Murtaza Bhai,

I want to use this is in my React Native Application. Is there an npm package available for this? How can I integrate this with my application?  You can mark this as a question it's not an issue just an informative question.

**Comment by mygulamali** [comment]
Hi @mustafa-taheri,

Thanks for your interest in this project. I never created it with the intention to be a Node module so I'm afraid there isn't a npm package. But it was written in ReactJS so it should be straightforward for you to use the core code in a React Native app.

The code for the calendar conversion calculations is in the  `source/assets/javascripts/_lib` directory. The ReactJS components are in the `source/assets/javascripts/_components` directory. They should be self explanatory, but please feel free to open another issue if you have any more questions.

I'm currently working on another version, which uses GatsbyJS instead of Middleman to generate the site. So hopefully a future version will have a `package.json` at least. 😬 Soon soon.

Thanks again!

**Comment by mustafa-taheri** [comment]
ThanQ for the response Bhai, I have seen the code but I got confused with so many things, The only thing I need from that this library is the Hijri Date and I know the `hijri_date.js` file will solve my problem. is there a way I can directly pass Georgian date to `hijri.fromGeorgian()` in my component. Basically this is what I am trying to achieve. 

![Screenshot from 2020-08-18 02-28-19](https://user-images.githubusercontent.com/20725410/90443995-bf0d7f00-e0fa-11ea-85e4-8024ecb50e73.png)

**Comment by mustafa-taheri** [comment]
@mygulamali Murataza Bhai, any suggestions..??

**Comment by mygulamali** [comment]
HI @mustafa-taheri, you should be able to pass a regular JS `Date` object to [`HijriDate.gregorianToAJD`](https://github.com/mygulamali/mumineen_calendar_js/blob/master/source/assets/javascripts/_lib/hijri_date.js#L95) to convert it into an Astronomical Julian Date (AJD). The AJD can then be converted into a `HijriDate` object using the [`HijriDate.fromAJD`](https://github.com/mygulamali/mumineen_calendar_js/blob/master/source/assets/javascripts/_lib/hijri_date.js#L165) method. This is essentially what the `fromGregorian` method does (see [here](https://github.com/mygulamali/mumineen_calendar_js/blob/master/source/assets/javascripts/_lib/hijri_date.js#L203)).

**Comment by mustafa-taheri** [comment]
Shukran @mygulamali Bhai, Your library is very helpful I have solved the issue and that fulfilled my purpose...  ThanQ again.. Closing this issue.

`Happy Coding Bhai...`
